; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev 
framework = arduino
build_flags = 
    -DCORE_DEBUG_LEVEL=5
    -D CONFIG_ASYNC_TCP_MAX_ACK_TIME=5000
    -D CONFIG_ASYNC_TCP_PRIORITY=10
    -D CONFIG_ASYNC_TCP_QUEUE_SIZE=64
    -D CONFIG_ASYNC_TCP_RUNNING_CORE=1
    -D CONFIG_ASYNC_TCP_STACK_SIZE=4096

monitor_speed = 115200

lib_deps = 
    https://github.com/prune74/CanUniversal.git
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer
    pierremolinaro/ACAN_ESP32
    pierremolinaro/ACAN2515
    bblanchon/ArduinoJson

debug_tool = esp-prog
debug_init_break = tbreak setup
